// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF18E6ytXLmRXc2-Ke6PPICEWePnM72_4',
    appId: '1:316856865434:android:e185263820271ce2ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCunzzU2CXM0-YJDPf2by0kSOzeZfTgW50',
    appId: '1:316856865434:ios:0d92f230783c2403ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCunzzU2CXM0-YJDPf2by0kSOzeZfTgW50',
    appId: '1:316856865434:ios:0d92f230783c2403ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd6vbcWJnTiGFMSO4Bdw32QytjademqwQ',
    appId: '1:316856865434:web:e6da70975b898f14ebc523',
    messagingSenderId: '316856865434',
    projectId: 'fruit-hub-b8e28',
    authDomain: 'fruit-hub-b8e28.firebaseapp.com',
    storageBucket: 'fruit-hub-b8e28.firebasestorage.app',
    measurementId: 'G-7N1EMBPFCH',
  );
}
